-- =============================================================================
-- Système de Gestion des Absences Étudiantes — Oracle 10g
-- Exécuter en tant que schéma applicatif technique (ex. OORACLE).
--
-- Login applicatif : géré par Django (tables AUTH_USER, etc. après migrate).
-- Ce script ne crée pas les utilisateurs finaux Oracle.
-- =============================================================================

-- Nettoyage (ordre inverse des dépendances) — commenter si première install
/*
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_SEANCE_BU';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ABSENCE_AIUD_QUOTA'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ABSENCE_BI_VALID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_INSCRIPTION_BI_ETU'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE BODY PKG_GESTION_ABSENCES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_GESTION_ABSENCES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HISTORIQUE_ALERTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ABSENCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PARAM_COURS_SEUIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEANCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INSCRIPTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ETUDIANT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COURS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ANNEE_UNIV CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FILIERE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
*/

-- -----------------------------------------------------------------------------
-- Tables métier
-- -----------------------------------------------------------------------------

CREATE TABLE FILIERE (
    ID_FILIERE      NUMBER          NOT NULL,
    CODE_FILIERE    VARCHAR2(10)    NOT NULL,
    NOM_FILIERE     VARCHAR2(100)   NOT NULL,
    CONSTRAINT PK_FILIERE PRIMARY KEY (ID_FILIERE),
    CONSTRAINT UK_FILIERE_CODE UNIQUE (CODE_FILIERE),
    CONSTRAINT CK_FILIERE_CODE_NN CHECK (LENGTH(TRIM(CODE_FILIERE)) > 0),
    CONSTRAINT CK_FILIERE_NOM_NN CHECK (LENGTH(TRIM(NOM_FILIERE)) > 0)
);

CREATE TABLE ANNEE_UNIV (
    ID_ANNEE        NUMBER          NOT NULL,
    LIBELLE         VARCHAR2(30)    NOT NULL,
    DATE_DEBUT      DATE            NOT NULL,
    DATE_FIN        DATE            NOT NULL,
    CONSTRAINT PK_ANNEE_UNIV PRIMARY KEY (ID_ANNEE),
    CONSTRAINT UK_ANNEE_LIB UNIQUE (LIBELLE),
    CONSTRAINT CK_ANNEE_DATES CHECK (DATE_FIN > DATE_DEBUT),
    CONSTRAINT CK_ANNEE_LIB_NN CHECK (LENGTH(TRIM(LIBELLE)) > 0)
);

CREATE TABLE COURS (
    ID_COURS        NUMBER          NOT NULL,
    CODE_COURS      VARCHAR2(20)    NOT NULL,
    INTITULE        VARCHAR2(200)   NOT NULL,
    COEF            NUMBER(4,2)     NOT NULL,
    NB_SEANCES_PREV NUMBER(5)       DEFAULT 30 NOT NULL,
    CONSTRAINT PK_COURS PRIMARY KEY (ID_COURS),
    CONSTRAINT UK_COURS_CODE UNIQUE (CODE_COURS),
    CONSTRAINT CK_COURS_COEF CHECK (COEF > 0 AND COEF <= 10),
    CONSTRAINT CK_COURS_NB_SE CHECK (NB_SEANCES_PREV > 0 AND NB_SEANCES_PREV <= 500),
    CONSTRAINT CK_COURS_INTITULE CHECK (LENGTH(TRIM(INTITULE)) > 0)
);

CREATE TABLE ETUDIANT (
    ID_ETUDIANT     NUMBER          NOT NULL,
    MATRICULE       VARCHAR2(20)    NOT NULL,
    NOM             VARCHAR2(80)    NOT NULL,
    PRENOM          VARCHAR2(80)    NOT NULL,
    EMAIL           VARCHAR2(120),
    DATE_NAISSANCE  DATE,
    ID_FILIERE      NUMBER          NOT NULL,
    STATUT          VARCHAR2(20)    DEFAULT 'ACTIF' NOT NULL,
    CONSTRAINT PK_ETUDIANT PRIMARY KEY (ID_ETUDIANT),
    CONSTRAINT UK_ETUDIANT_MAT UNIQUE (MATRICULE),
    CONSTRAINT UK_ETUDIANT_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_ETU_FILIERE FOREIGN KEY (ID_FILIERE) REFERENCES FILIERE (ID_FILIERE),
    CONSTRAINT CK_ETU_STATUT CHECK (STATUT IN ('ACTIF', 'SUSPENDU', 'DIPLOME')),
    CONSTRAINT CK_ETU_MAT CHECK (LENGTH(TRIM(MATRICULE)) > 0),
    CONSTRAINT CK_ETU_NOM CHECK (LENGTH(TRIM(NOM)) > 0),
    CONSTRAINT CK_ETU_PRENOM CHECK (LENGTH(TRIM(PRENOM)) > 0),
    CONSTRAINT CK_ETU_EMAIL_FMT CHECK (EMAIL IS NULL OR (INSTR(EMAIL, '@') > 1 AND LENGTH(EMAIL) >= 5))
);

CREATE TABLE INSCRIPTION (
    ID_INSCRIPTION  NUMBER          NOT NULL,
    ID_ETUDIANT     NUMBER          NOT NULL,
    ID_COURS        NUMBER          NOT NULL,
    ID_ANNEE        NUMBER          NOT NULL,
    DATE_INSC       DATE            DEFAULT SYSDATE NOT NULL,
    STATUT_INSC     VARCHAR2(20)    DEFAULT 'VALIDEE' NOT NULL,
    CONSTRAINT PK_INSCRIPTION PRIMARY KEY (ID_INSCRIPTION),
    CONSTRAINT FK_INS_ETU FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID_ETUDIANT),
    CONSTRAINT FK_INS_COURS FOREIGN KEY (ID_COURS) REFERENCES COURS (ID_COURS),
    CONSTRAINT FK_INS_ANNEE FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_UNIV (ID_ANNEE),
    CONSTRAINT UK_INS_ETU_COURS_AN UNIQUE (ID_ETUDIANT, ID_COURS, ID_ANNEE),
    CONSTRAINT CK_INS_STATUT CHECK (STATUT_INSC IN ('VALIDEE', 'ANNULEE'))
);

CREATE TABLE SEANCE (
    ID_SEANCE       NUMBER          NOT NULL,
    ID_COURS        NUMBER          NOT NULL,
    ID_ANNEE        NUMBER          NOT NULL,
    DATE_SEANCE     DATE            NOT NULL,
    HEURE_DEBUT     NUMBER(4,2)     NOT NULL,
    HEURE_FIN       NUMBER(4,2)     NOT NULL,
    STATUT_SEANCE   VARCHAR2(20)    DEFAULT 'PREVUE' NOT NULL,
    CONSTRAINT PK_SEANCE PRIMARY KEY (ID_SEANCE),
    CONSTRAINT FK_SEA_COURS FOREIGN KEY (ID_COURS) REFERENCES COURS (ID_COURS),
    CONSTRAINT FK_SEA_ANNEE FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_UNIV (ID_ANNEE),
    CONSTRAINT CK_SEA_HEURES CHECK (HEURE_FIN > HEURE_DEBUT AND HEURE_DEBUT >= 8 AND HEURE_FIN <= 22),
    CONSTRAINT CK_SEA_STATUT CHECK (STATUT_SEANCE IN ('PREVUE', 'REALISEE', 'ANNULEE')),
    CONSTRAINT UK_SEA_COURS_AN_DATE_HEURE UNIQUE (ID_COURS, ID_ANNEE, DATE_SEANCE, HEURE_DEBUT)
);

CREATE TABLE PARAM_GLOBAL_ANNEE (
    ID_ANNEE            NUMBER      NOT NULL,
    SEUIL_NON_JUSTIF    NUMBER(3)   NOT NULL,
    CONSTRAINT PK_PARAM_GLOBAL PRIMARY KEY (ID_ANNEE),
    CONSTRAINT FK_PG_ANNEE FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_UNIV (ID_ANNEE),
    CONSTRAINT CK_PG_SEUIL CHECK (SEUIL_NON_JUSTIF >= 1 AND SEUIL_NON_JUSTIF <= 50)
);

-- Clé surrogate ID_PARAM : Django 3 ne gère pas une PK composite proprement sur ce modèle.
CREATE TABLE PARAM_COURS_SEUIL (
    ID_PARAM        NUMBER          NOT NULL,
    ID_COURS        NUMBER          NOT NULL,
    ID_ANNEE        NUMBER          NOT NULL,
    SEUIL_NON_JUSTIF NUMBER(3)      NOT NULL,
    CONSTRAINT PK_PARAM_COURS_SEUIL PRIMARY KEY (ID_PARAM),
    CONSTRAINT UK_PCS_COURS_ANNEE UNIQUE (ID_COURS, ID_ANNEE),
    CONSTRAINT FK_PCS_COURS FOREIGN KEY (ID_COURS) REFERENCES COURS (ID_COURS),
    CONSTRAINT FK_PCS_ANNEE FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_UNIV (ID_ANNEE),
    CONSTRAINT CK_PCS_SEUIL CHECK (SEUIL_NON_JUSTIF >= 1 AND SEUIL_NON_JUSTIF <= 50)
);

CREATE TABLE ABSENCE (
    ID_ABSENCE      NUMBER          NOT NULL,
    ID_INSCRIPTION  NUMBER          NOT NULL,
    ID_SEANCE       NUMBER          NOT NULL,
    MOTIF           VARCHAR2(300),
    JUSTIFIEE       CHAR(1)         DEFAULT 'N' NOT NULL,
    DATE_SAISIE     DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ABSENCE PRIMARY KEY (ID_ABSENCE),
    CONSTRAINT FK_ABS_INS FOREIGN KEY (ID_INSCRIPTION) REFERENCES INSCRIPTION (ID_INSCRIPTION),
    CONSTRAINT FK_ABS_SEA FOREIGN KEY (ID_SEANCE) REFERENCES SEANCE (ID_SEANCE),
    CONSTRAINT UK_ABS_INS_SEANCE UNIQUE (ID_INSCRIPTION, ID_SEANCE),
    CONSTRAINT CK_ABS_JUST CHECK (JUSTIFIEE IN ('O', 'N'))
);

CREATE TABLE HISTORIQUE_ALERTE (
    ID_ALERTE       NUMBER          NOT NULL,
    ID_ETUDIANT     NUMBER          NOT NULL,
    ID_COURS        NUMBER          NOT NULL,
    ID_ANNEE        NUMBER          NOT NULL,
    NB_ABS_NON_JUST NUMBER(5)       NOT NULL,
    DATE_ALERTE     DATE            DEFAULT SYSDATE NOT NULL,
    MESSAGE         VARCHAR2(500)   NOT NULL,
    CONSTRAINT PK_HIST_ALERTE PRIMARY KEY (ID_ALERTE),
    CONSTRAINT FK_HA_ETU FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID_ETUDIANT),
    CONSTRAINT FK_HA_COURS FOREIGN KEY (ID_COURS) REFERENCES COURS (ID_COURS),
    CONSTRAINT FK_HA_ANNEE FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_UNIV (ID_ANNEE),
    CONSTRAINT CK_HA_NB CHECK (NB_ABS_NON_JUST >= 0)
);

-- -----------------------------------------------------------------------------
-- Séquences (Oracle 10g : pas de colonnes IDENTITY)
-- -----------------------------------------------------------------------------
-- Noms *_SQ : convention Django 3 (oracle.operations._get_no_autofield_sequence_name)
CREATE SEQUENCE FILIERE_SQ               START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ANNEE_UNIV_SQ            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COURS_SQ                 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ETUDIANT_SQ              START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INSCRIPTION_SQ           START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEANCE_SQ                START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ABSENCE_SQ               START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HISTORIQUE_ALERTE_SQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PARAM_COURS_SEUIL_SQ     START WITH 1 INCREMENT BY 1 NOCACHE;

-- -----------------------------------------------------------------------------
-- Triggers BEFORE INSERT : alimentation PK
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_FILIERE_BI
BEFORE INSERT ON FILIERE
FOR EACH ROW
BEGIN
    IF :NEW.ID_FILIERE IS NULL THEN
        SELECT FILIERE_SQ.NEXTVAL INTO :NEW.ID_FILIERE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ANNEE_UNIV_BI
BEFORE INSERT ON ANNEE_UNIV
FOR EACH ROW
BEGIN
    IF :NEW.ID_ANNEE IS NULL THEN
        SELECT ANNEE_UNIV_SQ.NEXTVAL INTO :NEW.ID_ANNEE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_COURS_BI
BEFORE INSERT ON COURS
FOR EACH ROW
BEGIN
    IF :NEW.ID_COURS IS NULL THEN
        SELECT COURS_SQ.NEXTVAL INTO :NEW.ID_COURS FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ETUDIANT_BI
BEFORE INSERT ON ETUDIANT
FOR EACH ROW
BEGIN
    IF :NEW.ID_ETUDIANT IS NULL THEN
        SELECT ETUDIANT_SQ.NEXTVAL INTO :NEW.ID_ETUDIANT FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INSCRIPTION_BI
BEFORE INSERT ON INSCRIPTION
FOR EACH ROW
BEGIN
    IF :NEW.ID_INSCRIPTION IS NULL THEN
        SELECT INSCRIPTION_SQ.NEXTVAL INTO :NEW.ID_INSCRIPTION FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SEANCE_BI
BEFORE INSERT ON SEANCE
FOR EACH ROW
BEGIN
    IF :NEW.ID_SEANCE IS NULL THEN
        SELECT SEANCE_SQ.NEXTVAL INTO :NEW.ID_SEANCE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ABSENCE_BI
BEFORE INSERT ON ABSENCE
FOR EACH ROW
BEGIN
    IF :NEW.ID_ABSENCE IS NULL THEN
        SELECT ABSENCE_SQ.NEXTVAL INTO :NEW.ID_ABSENCE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_HISTORIQUE_ALERTE_BI
BEFORE INSERT ON HISTORIQUE_ALERTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_ALERTE IS NULL THEN
        SELECT HISTORIQUE_ALERTE_SQ.NEXTVAL INTO :NEW.ID_ALERTE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PARAM_COURS_SEUIL_BI
BEFORE INSERT ON PARAM_COURS_SEUIL
FOR EACH ROW
BEGIN
    IF :NEW.ID_PARAM IS NULL THEN
        SELECT PARAM_COURS_SEUIL_SQ.NEXTVAL INTO :NEW.ID_PARAM FROM DUAL;
    END IF;
END;
/
