-- =============================================================================
-- Données de démonstration (optionnel)
-- Même jeu que : python manage.py seed_demo (étudiant DEMO001).
-- Après migrate Django sur Oracle, exécutez seed_demo pour créer AUTH_USER +
-- LIEN_COMPTE_ETUDIANT ; ce script seul ne crée pas le compte de connexion.
-- =============================================================================

INSERT INTO FILIERE (ID_FILIERE, CODE_FILIERE, NOM_FILIERE)
VALUES (NULL, 'INFO', 'Informatique de gestion');

INSERT INTO ANNEE_UNIV (ID_ANNEE, LIBELLE, DATE_DEBUT, DATE_FIN)
VALUES (NULL, '2024-2025', DATE '2024-09-01', DATE '2025-07-15');

INSERT INTO PARAM_GLOBAL_ANNEE (ID_ANNEE, SEUIL_NON_JUSTIF)
VALUES ((SELECT ID_ANNEE FROM ANNEE_UNIV WHERE LIBELLE = '2024-2025'), 3);

INSERT INTO COURS (ID_COURS, CODE_COURS, INTITULE, COEF, NB_SEANCES_PREV)
VALUES (NULL, 'BD501', 'Bases de données avancées', 3, 28);

INSERT INTO PARAM_COURS_SEUIL (ID_PARAM, ID_COURS, ID_ANNEE, SEUIL_NON_JUSTIF)
VALUES (
    NULL,
    (SELECT ID_COURS FROM COURS WHERE CODE_COURS = 'BD501'),
    (SELECT ID_ANNEE FROM ANNEE_UNIV WHERE LIBELLE = '2024-2025'),
    3
);

INSERT INTO ETUDIANT (ID_ETUDIANT, MATRICULE, NOM, PRENOM, EMAIL, DATE_NAISSANCE, ID_FILIERE, STATUT)
VALUES (
    NULL,
    'DEMO001',
    'Alami',
    'Sara',
    'sara.demo@etudiant.local',
    DATE '2002-05-10',
    (SELECT ID_FILIERE FROM FILIERE WHERE CODE_FILIERE = 'INFO'),
    'ACTIF'
);

INSERT INTO INSCRIPTION (ID_INSCRIPTION, ID_ETUDIANT, ID_COURS, ID_ANNEE, STATUT_INSC)
VALUES (
    NULL,
    (SELECT ID_ETUDIANT FROM ETUDIANT WHERE MATRICULE = 'DEMO001'),
    (SELECT ID_COURS FROM COURS WHERE CODE_COURS = 'BD501'),
    (SELECT ID_ANNEE FROM ANNEE_UNIV WHERE LIBELLE = '2024-2025'),
    'VALIDEE'
);

INSERT INTO SEANCE (ID_SEANCE, ID_COURS, ID_ANNEE, DATE_SEANCE, HEURE_DEBUT, HEURE_FIN, STATUT_SEANCE)
VALUES (
    NULL,
    (SELECT ID_COURS FROM COURS WHERE CODE_COURS = 'BD501'),
    (SELECT ID_ANNEE FROM ANNEE_UNIV WHERE LIBELLE = '2024-2025'),
    DATE '2024-10-15',
    14,
    16,
    'REALISEE'
);

INSERT INTO SEANCE (ID_SEANCE, ID_COURS, ID_ANNEE, DATE_SEANCE, HEURE_DEBUT, HEURE_FIN, STATUT_SEANCE)
VALUES (
    NULL,
    (SELECT ID_COURS FROM COURS WHERE CODE_COURS = 'BD501'),
    (SELECT ID_ANNEE FROM ANNEE_UNIV WHERE LIBELLE = '2024-2025'),
    DATE '2024-10-22',
    14,
    16,
    'REALISEE'
);

INSERT INTO SEANCE (ID_SEANCE, ID_COURS, ID_ANNEE, DATE_SEANCE, HEURE_DEBUT, HEURE_FIN, STATUT_SEANCE)
VALUES (
    NULL,
    (SELECT ID_COURS FROM COURS WHERE CODE_COURS = 'BD501'),
    (SELECT ID_ANNEE FROM ANNEE_UNIV WHERE LIBELLE = '2024-2025'),
    DATE '2024-10-29',
    14,
    16,
    'REALISEE'
);

INSERT INTO SEANCE (ID_SEANCE, ID_COURS, ID_ANNEE, DATE_SEANCE, HEURE_DEBUT, HEURE_FIN, STATUT_SEANCE)
VALUES (
    NULL,
    (SELECT ID_COURS FROM COURS WHERE CODE_COURS = 'BD501'),
    (SELECT ID_ANNEE FROM ANNEE_UNIV WHERE LIBELLE = '2024-2025'),
    DATE '2024-11-05',
    14,
    16,
    'REALISEE'
);

-- Evite ORA-04091 si ancienne version du trigger (sans fonction autonome) :
-- ALTER TRIGGER TRG_ABSENCE_AIUD_QUOTA DISABLE;
-- Apres correction du package (F_NB en transaction autonome), ce n'est plus obligatoire.

INSERT INTO ABSENCE (ID_ABSENCE, ID_INSCRIPTION, ID_SEANCE, MOTIF, JUSTIFIEE)
VALUES (
    NULL,
    (SELECT ID_INSCRIPTION FROM INSCRIPTION
     WHERE ID_ETUDIANT = (SELECT ID_ETUDIANT FROM ETUDIANT WHERE MATRICULE = 'DEMO001')
       AND ROWNUM = 1),
    (SELECT ID_SEANCE FROM SEANCE
     WHERE DATE_SEANCE = DATE '2024-10-15'
       AND ID_COURS = (SELECT ID_COURS FROM COURS WHERE CODE_COURS = 'BD501')
       AND ROWNUM = 1),
    'Rendez-vous médical',
    'O'
);

INSERT INTO ABSENCE (ID_ABSENCE, ID_INSCRIPTION, ID_SEANCE, MOTIF, JUSTIFIEE)
VALUES (
    NULL,
    (SELECT ID_INSCRIPTION FROM INSCRIPTION
     WHERE ID_ETUDIANT = (SELECT ID_ETUDIANT FROM ETUDIANT WHERE MATRICULE = 'DEMO001')
       AND ROWNUM = 1),
    (SELECT ID_SEANCE FROM SEANCE
     WHERE DATE_SEANCE = DATE '2024-10-22'
       AND ID_COURS = (SELECT ID_COURS FROM COURS WHERE CODE_COURS = 'BD501')
       AND ROWNUM = 1),
    'Transport en panne',
    'N'
);

COMMIT;
