# Generated by Django 3.0.14 on 2026-03-24 21:32
# Corrigé : CreateModel complets + ordre des dépendances (FK) pour l'état des migrations.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(db_column='ID_FILIERE', primary_key=True, serialize=False)),
                ('code_filiere', models.CharField(db_column='CODE_FILIERE', max_length=10)),
                ('nom_filiere', models.CharField(db_column='NOM_FILIERE', max_length=100)),
            ],
            options={
                'db_table': 'FILIERE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnneeUniv',
            fields=[
                ('id_annee', models.AutoField(db_column='ID_ANNEE', primary_key=True, serialize=False)),
                ('libelle', models.CharField(db_column='LIBELLE', max_length=30)),
                ('date_debut', models.DateField(db_column='DATE_DEBUT')),
                ('date_fin', models.DateField(db_column='DATE_FIN')),
            ],
            options={
                'db_table': 'ANNEE_UNIV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(db_column='ID_COURS', primary_key=True, serialize=False)),
                ('code_cours', models.CharField(db_column='CODE_COURS', max_length=20)),
                ('intitule', models.CharField(db_column='INTITULE', max_length=200)),
                ('coef', models.DecimalField(db_column='COEF', decimal_places=2, max_digits=4)),
                ('nb_seances_prev', models.IntegerField(db_column='NB_SEANCES_PREV')),
            ],
            options={
                'verbose_name_plural': 'cours',
                'db_table': 'COURS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.AutoField(db_column='ID_ETUDIANT', primary_key=True, serialize=False)),
                ('matricule', models.CharField(db_column='MATRICULE', max_length=20, unique=True)),
                ('nom', models.CharField(db_column='NOM', max_length=80)),
                ('prenom', models.CharField(db_column='PRENOM', max_length=80)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=120, null=True, unique=True)),
                ('date_naissance', models.DateField(blank=True, db_column='DATE_NAISSANCE', null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('DIPLOME', 'Diplômé')], db_column='STATUT', default='ACTIF', max_length=20)),
                ('id_filiere', models.ForeignKey(db_column='ID_FILIERE', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Filiere')),
            ],
            options={
                'db_table': 'ETUDIANT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id_inscription', models.AutoField(db_column='ID_INSCRIPTION', primary_key=True, serialize=False)),
                ('date_insc', models.DateField(db_column='DATE_INSC')),
                ('statut_insc', models.CharField(choices=[('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], db_column='STATUT_INSC', default='VALIDEE', max_length=20)),
                ('id_annee', models.ForeignKey(db_column='ID_ANNEE', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.AnneeUniv')),
                ('id_cours', models.ForeignKey(db_column='ID_COURS', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Cours')),
                ('id_etudiant', models.ForeignKey(db_column='ID_ETUDIANT', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Etudiant')),
            ],
            options={
                'db_table': 'INSCRIPTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id_seance', models.AutoField(db_column='ID_SEANCE', primary_key=True, serialize=False)),
                ('date_seance', models.DateField(db_column='DATE_SEANCE')),
                ('heure_debut', models.DecimalField(db_column='HEURE_DEBUT', decimal_places=2, max_digits=4)),
                ('heure_fin', models.DecimalField(db_column='HEURE_FIN', decimal_places=2, max_digits=4)),
                ('statut_seance', models.CharField(choices=[('PREVUE', 'Prévue'), ('REALISEE', 'Réalisée'), ('ANNULEE', 'Annulée')], db_column='STATUT_SEANCE', default='PREVUE', max_length=20)),
                ('id_annee', models.ForeignKey(db_column='ID_ANNEE', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.AnneeUniv')),
                ('id_cours', models.ForeignKey(db_column='ID_COURS', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Cours')),
            ],
            options={
                'db_table': 'SEANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParamGlobalAnnee',
            fields=[
                ('id_annee', models.OneToOneField(db_column='ID_ANNEE', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='absence.AnneeUniv')),
                ('seuil_non_justif', models.IntegerField(db_column='SEUIL_NON_JUSTIF')),
            ],
            options={
                'db_table': 'PARAM_GLOBAL_ANNEE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParamCoursSeuil',
            fields=[
                ('id_param', models.AutoField(db_column='ID_PARAM', primary_key=True, serialize=False)),
                ('seuil_non_justif', models.IntegerField(db_column='SEUIL_NON_JUSTIF')),
                ('id_annee', models.ForeignKey(db_column='ID_ANNEE', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.AnneeUniv')),
                ('id_cours', models.ForeignKey(db_column='ID_COURS', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Cours')),
            ],
            options={
                'db_table': 'PARAM_COURS_SEUIL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(db_column='ID_ABSENCE', primary_key=True, serialize=False)),
                ('motif', models.CharField(blank=True, db_column='MOTIF', max_length=300, null=True)),
                ('justifiee', models.CharField(db_column='JUSTIFIEE', default='N', max_length=1)),
                ('date_saisie', models.DateTimeField(db_column='DATE_SAISIE')),
                ('id_inscription', models.ForeignKey(db_column='ID_INSCRIPTION', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Inscription')),
                ('id_seance', models.ForeignKey(db_column='ID_SEANCE', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Seance')),
            ],
            options={
                'db_table': 'ABSENCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAlerte',
            fields=[
                ('id_alerte', models.AutoField(db_column='ID_ALERTE', primary_key=True, serialize=False)),
                ('nb_abs_non_just', models.IntegerField(db_column='NB_ABS_NON_JUST')),
                ('date_alerte', models.DateTimeField(db_column='DATE_ALERTE')),
                ('message', models.CharField(db_column='MESSAGE', max_length=500)),
                ('id_annee', models.ForeignKey(db_column='ID_ANNEE', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.AnneeUniv')),
                ('id_cours', models.ForeignKey(db_column='ID_COURS', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Cours')),
                ('id_etudiant', models.ForeignKey(db_column='ID_ETUDIANT', on_delete=django.db.models.deletion.DO_NOTHING, to='absence.Etudiant')),
            ],
            options={
                'db_table': 'HISTORIQUE_ALERTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilEtudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profil_compte', to='absence.Etudiant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LIEN_COMPTE_ETUDIANT',
            },
        ),
    ]
