# Generated by Django 3.0.14 on 2026-03-24 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _creer_groupes_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in ('Etudiant', 'Enseignant', 'Scolarite', 'Admin_application'):
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absence', '0002_sqlite_schema_metier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointageGPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexte', models.CharField(help_text='Ex. Arrivée campus, justification de déplacement', max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Précision (m)')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages_gps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pointage GPS',
                'verbose_name_plural': 'pointages GPS',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='NotificationApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_app', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications applicatives',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.RunPython(_creer_groupes_roles, migrations.RunPython.noop),
    ]
