"""
Django settings for projet_oracle project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/

Projet cible : serveur Oracle Database 10g uniquement.
- Pas de mode thin (non supporte vers 10g). Connexion via Instant Client 64 bits en mode epais.
- ORACLE_CLIENT_LIB = dossier Instant Client (ex. 19c) : ce client se connecte au serveur 10g.
- ORACLE_STRIP_LEGACY_PATH : retirer le bin du serveur XE 10 local (souvent 32 bits) du PATH.
"""
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

_strip_flag = os.environ.get("ORACLE_STRIP_LEGACY_PATH", "").lower()
if _strip_flag in ("0", "false", "no", "off"):
    _strip_path = False
elif _strip_flag in ("1", "true", "yes", "on"):
    _strip_path = True
else:
    # Windows : par defaut retirer XE 10 / oraclexe du PATH (evite oci 32 bits avec Python 64 bits).
    _strip_path = sys.platform == "win32"

if _strip_path:
    _sep = os.pathsep
    _bad = ("oraclexe", "10.2.0", "product\\10.", "product/10.")
    _paths = [
        p
        for p in os.environ.get("PATH", "").split(_sep)
        if p and not any(b in p.replace("/", "\\").lower() for b in _bad)
    ]
    os.environ["PATH"] = _sep.join(_paths)

_oracle_client_lib = os.environ.get("ORACLE_CLIENT_LIB", "").strip()

try:
    import oracledb

    if _oracle_client_lib:
        oracledb.init_oracle_client(lib_dir=_oracle_client_lib)
        sys.modules.setdefault("cx_Oracle", oracledb)
except ImportError:
    pass
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'pn)b67g6hicafbvz$6x(s5goe7qpqv=&8e*9js5r@g4ua2d*pw',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

_allowed = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed.split(',') if h.strip()]
    if _allowed
    else ['127.0.0.1', 'localhost']
)

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/tableau-de-bord/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'absence.apps.AbsenceConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projet_oracle.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'absence.context_processors.app_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'projet_oracle.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# -----------------------------------------------------------------------------
# Oracle — creation du compte (a executer en SYS AS SYSDBA dans SQL*Plus / SQL Developer)
# Remplacez le mot de passe en production. Meme utilisateur pour posseder les tables
# SQL (scripts oracle/01, 02) et pour Django ci-dessous (ORACLE_USER).
#
#   CREATE USER ABS_APP IDENTIFIED BY "1234"
#     DEFAULT TABLESPACE USERS
#     QUOTA UNLIMITED ON USERS;
#
#   GRANT CREATE SESSION TO ABS_APP;
#   GRANT CREATE TABLE TO ABS_APP;
#   GRANT CREATE SEQUENCE TO ABS_APP;
#   GRANT CREATE PROCEDURE TO ABS_APP;
#   GRANT CREATE TRIGGER TO ABS_APP;
#
# Ensuite : connecter ABS_APP, executer oracle/01_tables_sequences.sql puis
# oracle/02_package_and_triggers.sql ; copier .env.example vers .env si besoin,
# puis : python manage.py migrate && python manage.py seed_demo
# -----------------------------------------------------------------------------

# Base unique : Oracle 10g. ORACLE_NAME = SID ou service (souvent XE).
ORACLE_USER = os.environ.get('ORACLE_USER', 'ABS_APP')
ORACLE_PASSWORD = os.environ.get('ORACLE_PASSWORD', '1234')
ORACLE_NAME = os.environ.get('ORACLE_NAME', 'XE')
ORACLE_HOST = os.environ.get('ORACLE_HOST', 'localhost')
ORACLE_PORT = os.environ.get('ORACLE_PORT', '1521')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': ORACLE_NAME,
        'USER': ORACLE_USER,
        'PASSWORD': ORACLE_PASSWORD,
        'HOST': ORACLE_HOST,
        'PORT': ORACLE_PORT,
    }
}

# Django 3 cible Oracle 12c+ (IDENTITY, OFFSET/FETCH). Oracle 10g : patchs locaux.
from .oracle10g_compat import apply_patches

apply_patches()


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Casablanca'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
